namespace Microsoft.Cci.Pdb
{
	internal enum CV_GENERIC_STYLE
	{
		CV_GENERIC_VOID = 0,
		CV_GENERIC_REG = 1,
		CV_GENERIC_ICAN = 2,
		CV_GENERIC_ICAF = 3,
		CV_GENERIC_IRAN = 4,
		CV_GENERIC_IRAF = 5,
		CV_GENERIC_UNUSED = 6
	}
}
